spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/treinamentob
    username: postgres
    password: admin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 8080
